EcartApplication/Models/ErrorViewModel.cs
using System;

namespace EcartApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EcartApplication/Models/PromotionClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Threading.Tasks;

namespace EcartApplication.Models
{
    public class PromotionClass
    {

        public decimal CalculatePromo(IEnumerable<Skudetail> _Product)
        {
            decimal netamount = 0.0M;
            Promo group1 = new Promo();
            Promo group2 = new Promo();
            Promo group3 = new Promo();
            bool statusflg = true;
            group1.Promopercentage = 13.34F;
            group2.Promopercentage = 25.0f;
            group3.Promopercentage = 30.0f;




            foreach (var item in _Product)
            {
                if (item.Unitname == "A")
                {
                    int remainder;
                    int quotient = Math.DivRem(item.Unitqty, 3, out remainder);
                    int val1 = item.Unitqty - remainder;
                    //var afd = val1 * item.unitprice - (val1 * item.unitprice * group1.Promopercentage / 100);
                    decimal suma = Convert.ToDecimal((val1 * item.unitprice - (val1 * item.unitprice * group1.Promopercentage / 100)) + remainder * item.unitprice);
                    netamount += Math.Round(suma);

                }
                else if (item.Unitname == "B")
                {
                    int remainder;
                    int quotient = Math.DivRem(item.Unitqty, 2, out remainder);
                    int val1 = item.Unitqty - remainder;
                    netamount += Convert.ToDecimal((val1 * item.unitprice - (val1 * item.unitprice * group2.Promopercentage / 100)) + remainder * item.unitprice);

                }
                else if (item.Unitname == "C" || item.Unitname == "D")
                {
                    var cnt = (from val in _Product where (val.Unitname == "C" || val.Unitname == "D") select val).Count();
                    if (statusflg == true)
                    {
                        if (cnt > 1)
                        {

                            var unitqtyC = (from val in _Product where (val.Unitname == "C") select val.Unitqty).ToList();
                            var unitqtyD = (from val in _Product where (val.Unitname == "D") select val.Unitqty).ToList();
                            int remainderc, remainderD, remcd;
                            int qutientcd =Math.DivRem(unitqtyC[0] + unitqtyD[0], 2, out remcd);
                            if (remcd == 0)
                            {
                                netamount += ((unitqtyC[0] + unitqtyD[0])/2 )* 30;
                            }
                            else {
                                int quotientc = Math.DivRem(unitqtyC[0], 2, out remainderc);
                                int quotientd = Math.DivRem(unitqtyD[0], 2, out remainderD);

                                netamount += (quotientc + quotientd) * 30;
                                if (remainderc > 0)
                                {
                                    netamount += remainderc * 20;
                                }
                                if (remainderD > 0)
                                {
                                    netamount += remainderD * 15;
                                }
                            }
                            statusflg = false;

                        }
                        else if (item.Unitname == "C")
                        {
                            netamount += item.Unitqty * item.unitprice;
                        }
                        else if (item.Unitname == "D")
                        {
                            netamount += item.Unitqty * item.unitprice;
                        }
                        statusflg = false;
                    }


                }



            }
            return netamount;

        }
    }
}

EcartApplication/Models/PropClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EcartApplication.Models
{
    public class Product
    {
        public List<Skudetail> listSkudetail { get; set; }
    }

    public class Skudetail
    {
        public string Unitname { get; set; }
        public int Unitqty { get; set; }
        public int unitprice { get; set; }

        public decimal Unittotal { get; set; }
        public int total { get; set; }
    }

    public class Promo
    {
        public float Promopercentage { get; set; }
    }

}

EcartApplication/Controllers/ECartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EcartApplication.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EcartApplication.Controllers
{
    public class ECartController : Controller
    {
        [HttpGet]
        public IActionResult UserCart()
        {    
            var _skudetail = new List<Skudetail>()
            {
            new Skudetail(){ Unitname = "A", unitprice = 50 },
            new Skudetail(){ Unitname = "B", unitprice = 30 },
            new Skudetail(){ Unitname = "C", unitprice = 20 },
            new Skudetail(){ Unitname = "D", unitprice = 15 }
            };
            return View(_skudetail);
        }
        
        [HttpPost]
        public IActionResult UserCart(IEnumerable<Skudetail> _skudetail)
        {
            PromotionClass promoclass = new PromotionClass();
            var netamount = promoclass.CalculatePromo(_skudetail);
            ViewBag.netamount = netamount.ToString();
            return View(_skudetail);
        }
    }
}

EcartApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using EcartApplication.Models;

namespace EcartApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
         //home controller
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EcartApplication/Views/ECart/UserCart.cshtml
@model IList<EcartApplication.Models.Skudetail>
@{
    ViewData["Title"] = "UserCart";
}

<div class="row">
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-3 ">
                <div class="card text-center">
                    <h1 class="card-img-top  text-black-50">A</h1>

                    <div class="card-body">
                        <h4 class="card-title">Price</h4>
                        <h3 class="card-text  text-success">50</h3>
                        <h6>Promotion</h6>
                        <h4 class="text-primary">3 A's for 130</h4>
                    </div>
                </div>
            </div>
            <div class="col-md-3 ">
                <div class="card text-center">
                    <h1 class="card-img-top  text-black-50">B</h1>

                    <div class="card-body">
                        <h4 class="card-title">Price</h4>
                        <h3 class="card-text  text-success">30</h3>
                        <h6>Promotion</h6>
                        <h4 class="text-primary">2 B's for 45</h4>
                    </div>
                </div>
            </div>
            <div class="col-md-3 ">
                <div class="card text-center">
                    <h1 class="card-img-top  text-black-50">C</h1>

                    <div class="card-body">
                        <h4 class="card-title">Price</h4>
                        <h3 class="card-text  text-success">20</h3>
                        <h6>Promotion</h6>
                        <h4 class="text-primary">C & D for 30</h4>
                    </div>
                </div>
            </div>
            <div class="col-md-3 ">
                <div class="card text-center">
                    <h1 class="card-img-top  text-black-50">D</h1>

                    <div class="card-body">
                        <h4 class="card-title">Price</h4>
                        <h3 class="card-text  text-success">15</h3>
                        <h6>Promotion</h6>
                        <h4 class="text-primary">C & D for 30</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-4 shadow p-3 mb-5 bg-white rounded">
        <div class="row">
            <div>
                @using (Html.BeginForm("UserCart", "ECart", FormMethod.Post))
                {
                    <h3 class="text-center text-black-50 ">Cart</h3>
                    <hr class="col-md-12" />
                    @if (Model != null)
                    {
                        for (int i = 0; i < Model.Count(); i++)
                        {
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-2 text-right">
                                        @Html.DisplayFor(model => Model[i].Unitname)
                                    </div>
                                    <div class="col-md-2">
                                        @Html.Label("*")
                                    </div>
                                    <div class="col-md-3">
                                        @Html.TextBoxFor(m => Model[i].Unitqty, new { @style = " width:40px; ", autocomplete = "off" })
                                    </div>
                                    <div class="col-md-2">
                                        @Html.Label("=")
                                    </div>
                                    <div class="col-md-3">
                                        @Html.TextBoxFor(m => Model[i].Unittotal, new { @style = " width:80px; ", @readonly = "readonly" })
                                    </div>
                                </div>
                            </div>
                            @Html.HiddenFor(m => Model[i].Unitname)
                            @Html.HiddenFor(m => Model[i].unitprice)
                            
                        }


                    }
                    <div class="form-group ">
                        <div class="row">
                            <div class="offset-md-2 col-md-5 text-lg-right">
                                @Html.Label("Total")
                            </div>
                            <div class="col-md-1">
                                @Html.Label("=")
                            </div>
                            <div class="offset-md-1 col-md-2 text-lg-right offset-md-1">                               
                                @Html.Label("", null, new { @id = "totalval" })
                            </div>
                        </div>



                    </div>



                    <div class="form-group">
                        <div class="row">
                            <div class="offset-md-1 col-md-11">
                                <div class="col-md-9">
                                    <small class="text-right text-success">Apply Promotion click here</small>
                                </div>
                                <div class="col-md-3">
                                    <button value="Save" type="submit" class="btn btn-primary float-left">Apply</button>
                                </div>
                            </div>
                        </div>

                    </div>
                    <br />
                    <div class="form-group">
                        <div class="row">
                            <div class="offset-md-2 col-md-5">
                                @Html.Label("Net Amount")
                            </div>
                            <div class="col-md-1">
                                @Html.Label("=")
                            </div>
                            <div class="offset-md-1 col-md-2 text-lg-right text-success">
                                @Html.Label("",(string)ViewBag.netamount,new { @id="netval"})
                            </div>
                        </div>

                    </div>

                    <br />
                    <div class="form-group">
                        <div class="row">
                            <div class="offset-md-1 col-md-11">
                                <button type="button" id="clear" class="btn btn-dark">Clear cart</button>
                                <button type="button" class="btn btn-success">Pay Now</button>

                            </div>
                        </div>


                    </div>

                }
            </div>
        </div>
    </div>

</div>

@section MyScripts {
    <script>
        $(function () {

            $("#totalval").text(parseInt($("#z0__Unittotal").val() || 0) + parseInt($("#z1__Unittotal").val() || 0) + parseInt($("#z2__Unittotal").val() || 0) + parseInt($("#z3__Unittotal").val() || 0));

            $("#z0__Unitqty").change(function () {
                $("#z0__Unittotal").val($(this).val() * 50);
                $("#totalval").text(parseInt($("#totalval").val() || 0) + parseInt(($(this).val() * 50)));

            });
            $("#z1__Unitqty").change(function () {
                $("#z1__Unittotal").val($(this).val() * 30);
                $("#totalval").text(parseInt($("#totalval").text()) + parseInt(($(this).val() * 30)));
            });
            $("#z2__Unitqty").change(function () {
                $("#z2__Unittotal").val($(this).val() * 20);
                $("#totalval").text(parseInt($("#totalval").text() || 0) + parseInt(($(this).val() * 20)));
            });
            $("#z3__Unitqty").change(function () {
                $("#z3__Unittotal").val($(this).val() * 15);
                $("#totalval").text(parseInt($("#totalval").text() || 0) + parseInt(($(this).val() * 15)));
            });
            $("#clear").click(function () {
                $("#z0__Unitqty").val('');
                $("#z1__Unitqty").val('');
                $("#z2__Unitqty").val('');
                $("#z3__Unitqty").val('');

                $("#z0__Unittotal").val('');
                $("#z1__Unittotal").val('');
                $("#z2__Unittotal").val('');
                $("#z3__Unittotal").val('');
                $("label[id*=totalval").text('');
                $('label[id*="netval"]').text('');
            });
        });
    </script>
}

EcartApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EcartApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EcartApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EcartApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EcartApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
   
    @RenderSection("Scripts", required: false)
    @RenderSection("MyScripts", required: false)
</body>
</html>